// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elmjtvhdnnjemzaoshuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbWp0dmhkbm5qZW16YW9zaHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTAyODAsImV4cCI6MjA3MTk2NjI4MH0.mw53FGxngzHHPAB3yscZ3JsYgVJtvct8_UGOTNFsVwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});